### ISSUE TITLE
Toggle Explicit Content Filter

### ISSUE THREAD

**Issue by JasonLG1979** [PromyLOPh/pandora-apidoc#15]
The Explicit Content Filter can be toggled with:

Method: 
user.setExplicitContentFilter

arg:
isExplicitContentFilterEnabled : <i>boolean</i>

It returns nothing and has no effect if the Explicit Content Filter is PIN Protected. The state of the filter and PIN protection can ofc be checked with user.getSettings. It doesn't take effect until the next playlist.(i.e. any prior uncensored playlist does not magically become censored and vice-versa)

I added the feature to Pithos a while ago.
 https://github.com/pithos/pithos/commit/50aa53694e6267e9a995915201d540b645cf0bd9

I'd do a direct pull request for this but I barely know what I'm doing on git/github,lol!!!

**Comment by PromyLOPh** [comment]
The method I’m using with pianobar is already documented:
https://6xq.net/pandora-apidoc/json/account/#user-changesettings

> I'd do a direct pull request for this but I barely know what I'm doing
> on git/github,lol!!!
Go ahead, you can’t break anything.

**Comment by JasonLG1979** [comment]
user.changeSettings isExplicitContentFilterEnabled : <i>boolean</i>

causes a code 9 error

**Comment by PromyLOPh** [comment]
Interesting, it works for me. Did you include all the required
parameters (pianobar code:
https://github.com/PromyLOPh/pianobar/blob/master/src/libpiano/request.c#L407)?

**Comment by JasonLG1979** [comment]
I was missing 'userInitiatedChange' (is that documented?) 'currentUsername' and 'currentPassword' Pithos doesn't user the user's password and username for anything but initial authentication from then on it uses the userAuthToken(we don't even storing it as an object in pandora.py, I had to modify the code slightly to get user.changeSettings isExplicitContentFilterEnabled to work) so it's more convenient for us to use user.setExplicitContentFilter   isExplicitContentFilterEnabled : boolean.

**Comment by PromyLOPh** [comment]
> I was missing 'userInitiatedChange' (is that documented?) 'currentUsername' and 'currentPassword'
Yes, these are documented, userInitiatedChange is optional.

> […] so it's more convenient for us to use user.setExplicitContentFilter   isExplicitContentFilterEnabled : boolean.
I see.
