### ISSUE TITLE
Help! Can't even get my partner login.

### ISSUE THREAD

**Issue by FireController1847** [PromyLOPh/pandora-apidoc#22]
http://tuner.pandora.com/services/json/?method=auth.partnerLogin&username=android&password=AC7IBG09A3DTSYM4R41UJWL07VLN8JI7&deviceModel=android-generic&version=5&includeUrls=false&returnDeviceType=false&returnUpdatePromptVersions=false

I'm trying this, and I've tried various other usernames and passwords as well, but they all end in Code: 9. I can't figure out what value I'm missing, I have EVERYTHING listed in the docs.

**Comment by PromyLOPh** [comment]
Only the four values listed here[1] are URL parameters. Everything else
is part of a JSON object in the request body, see example at [2].

[1] https://6xq.net/pandora-apidoc/json/
[2] https://6xq.net/pandora-apidoc/json/authentication/#partner-login

**Comment by FireController1847** [comment]
@PromyLOPh Wow, I feel so dumb. Thanks for the help! :D

**Comment by balutaeugen** [comment]
So yeah.
I'm writing this "parameteres" in POST body, still getting this error
