### ISSUE TITLE
Many APIs broken

### ISSUE THREAD

**Issue by hacker1024** [PromyLOPh/pandora-apidoc#36]
It looks like a ton of APIs just changed or broke. None of the JSON-based clients I used seem to be able to log in (I was using one as this happened, and it failed to fetch the playlist, so looks like that's broken also).

My own REST-based app can't load the station list anymore (looks like `getShuffle`, is just, gone, as well as other things changing).

Hopefully, things have just changed and we won't lose any functionality long-term. I hope this isn't a sign that the Pandora devs have finally learnt to build secure APIs...

**Comment by hacker1024** [comment]
Oh, I just checked their website... Looks like they're just doing maintenance. Will close this issue once they've finished and we can see if anything changes.

**Comment by PromyLOPh** [comment]
Works for me right now. Still an issue?

**Comment by hacker1024** [comment]
Yup, the web interface itself complains if you try to shuffle atm.

**Comment by hacker1024** [comment]
Turns out using `getStations` in my app now gives back a 500 status code and the following JSON:

```
{message: Internal server error, errorCode: 0}
```

Figured I'd mention this because it can be useful to prepare for this error in our apps now.

It's odd, because the above API seems to work fine in the web app...

I'm not going to spend much time investigating unless the issue remains after the maintenance, though.

**Comment by hacker1024** [comment]
More info: Looks like it's the REST `v1/listener/getProfile` (and probably the JSON equivilent) endpoint breaking logins. Same response as described above.

**Comment by hacker1024** [comment]
Everything seems good now.
