### ISSUE TITLE
[REST] Logging in with an existing auth token

### ISSUE THREAD

**Issue by hacker1024** [PromyLOPh/pandora-apidoc#44]
When opening the Pandora Web client, after having signed in already, it seems to log In with a request like the following, with an empty password string and a populated `existingAuthToken` field:

```HTTP
POST https://www.pandora.com/api/v1/auth/login
```
```json
{
  "existingAuthToken": "<token>",
  "username": "email@addre.ss",
  "password": "",
  "keepLoggedIn":true
}
```

The existing auth token is always the one that was received when logging in previously.

Upon replicating this request, however, I get the standard invalid credential error:

```json
{
  "message": "Invalid username and/or password",
  "errorCode": 0,
  "errorString": "AUTH_INVALID_USERNAME_PASSWORD"
}
```

Does anyone know what's going on here?

**Comment by hacker1024** [comment]
Closing as this is no longer relevant (#45)

**Comment by GodStar88** [comment]
![Untitled](https://user-images.githubusercontent.com/23701978/111105508-17700680-858e-11eb-8f02-dc70f3608e73.png)

{
    "message": "The request could not be validated",
    "errorCode": 0,
    "errorString": "INVALID_REQUEST"
}

how can i get existing auth token?

**Comment by GodStar88** [comment]
![Untitled](https://user-images.githubusercontent.com/23701978/111105573-45ede180-858e-11eb-891d-d5bfb7fbfbc7.png)



{
    "existingAuthToken": null,
    "keepLoggedIn": true,
    "password": "dfssdf345",
    "username": "go@gmail.com"
    }

{
    "message": "The request could not be validated",
    "errorCode": 0,
    "errorString": "INVALID_REQUEST"
}

how can i get existing auth token?

**Comment by hacker1024** [comment]
The only way now is through the JSON API

**Comment by GodStar88** [comment]
Ok, do you have skype?

**Comment by H0r53** [comment]
@hacker1024 is there a basic example for User Login via the JSON API using something like CURL? I just want to make some simple requests to workaround this issue (migrating from REST API) and the docs aren't very clear to me.
