### ISSUE TITLE
Partner updates

### ISSUE THREAD

**Issue by hacker1024** [PromyLOPh/pandora-apidoc#48]
At some point, the android app seems to have switched to `android-tuner.pandora.com`, though the old subdomain still works. Everything else remains the same.

Additionally, I have extracted the following partner details from version 8.7.1 of the Android app. Perhaps they can be added to the documentation for the sake of completeness? It still works. I tried making a PR, but I can't seem to get the RST tables to play nicely with my additions.

|||
|-|-|
|**Username**|`android-gtv`|
|**Password**|`^bs2*tzZAM47tvmAvV1GZS^TH1SBW?8o`|
|**Device ID**|`gtv2-foster`|
|**Encrypt key**|`MCf5Ljj*V?Fr4cF4`|
|**Decrypt key**|`2lSj00N1fKYfOk8x`|

**Comment by PromyLOPh** [comment]
Added with dc40fd41fc895346a873412ef177d3a3ccf451de, thank you!

**Comment by hacker1024** [comment]
@PromyLOPh Sorry, I should have been clearer - the partner credentials I found were extracted from a very old version of the Android app. The credentials from before are the most recent.

This is important, as using the old credentials actually seems to result in old JSON structures being returned by the backend which don't contain new things added in later versions.

**Comment by PromyLOPh** [comment]
Whoops, fixed with e5d08bf95b3ecd193b1917b07d566df1e9f849de
