### ISSUE TITLE
Key source

### ISSUE THREAD

**Issue by 89z** [PromyLOPh/pandora-apidoc#53]
I am trying to find the source of this key:

https://github.com/PromyLOPh/pandora-apidoc/blame/master/json/partners.rst#L20

added here:

https://github.com/PromyLOPh/pandora-apidoc/commit/943c1b50abf1585744963b0eb3478b5e18141656

**Comment by 89z** [comment]
Found it:

~~~java
com\pandora\constants\PandoraConstants.java
8:    public static final byte[] b = "6#26FRL$ZWD".getBytes(Charset.defaultCharset());
~~~

https://github.com/skylot/jadx

**Comment by PromyLOPh** [comment]
Alright. Don’t expect any help from me if

1) you [cross-post](https://github.com/PromyLOPh/pianobar/issues/726) your question to multiple locations and
2) your quest is to build a downloader for Pandora.

**Comment by 89z** [comment]
> 1. you [cross-post](https://github.com/PromyLOPh/pianobar/issues/726) your question to multiple locations 

I post many issues. Sometimes duplicates get posted. This happens when the same person has two of essentially the same repo. Sorry about that, but its a consequence of people maintaining two repos that are similar enough that they should be merged, combined with my inattention.

>  2. your quest is to build a downloader for Pandora.

Regardless of what my quest might be, I think its important to not have "magic numbers" in a repo. If something happens to you, like you get busy and just cant commit anymore, and Pandora changes the key, people wont be able to use the tools, as they wont have a valid key, they wont know how to get a new key, and they wont even know where the old key came from. So while having the key publicly posted is helpful, its ultimately not helpful enough, in my opinion. Ive since answered my own question, and I will document the process in my own code.
