### ISSUE TITLE
Error Code 3 on User Authentication

### ISSUE THREAD

**Issue by SuperGeekJake** [PromyLOPh/pandora-apidoc#8]
I'm unsure as to why I would be continually receiving a fail response on user authentication with the error code 3.

[Project Repo](https://github.com/SuperGeekJake/atomized-pandora)

**Comment by winny-** [comment]
I see the following parameters: `/services/json/?method=auth.userLogin&partner_id=42`

Your user login request is missing the auth token. http://6xq.net/playground/pandora-apidoc/json/errorcodes/

http://6xq.net/playground/pandora-apidoc/json/ explains the url parameters that should be in most requests. And here's an example of what values should be in the URL: https://github.com/HermesApp/Hermes/blob/master/Sources/Pandora/Pandora.m#L806-L814

Hope this helps.

**Comment by SuperGeekJake** [comment]
Whoops, completely skipped over reading everything passed *User auth token*. Thanks so much for your reply.

**Comment by winny-** [comment]
Good luck on your Pandora client! :pizza:
