### ISSUE TITLE
conversion to hex after encryption

### ISSUE THREAD

**Issue by Mitchell-Findley** [PromyLOPh/pandora-apidoc#9]
I have had some trouble posting with uppercase letter hex. These issues went away when i saw all incoming in was lowercase hex. I switched mine to always send lowercase hex and the errors went poof. I think this should be documented as hex strings are supposed to be uppercase.

**Comment by seliver** [comment]
You mean "supposed to be lowercase".

**Comment by PromyLOPh** [comment]
Fixed, see aa39278d93c6a3f803db968a86e8a9ef499acd48
